### ISSUE TITLE
Binding failed: 10049 !

### ISSUE THREAD

**Issue by subhampro** [wow0000/GRE_Tunnel#2]
![image](https://user-images.githubusercontent.com/33375250/184964921-3c0d8c48-a83c-4429-8c9a-0324c3fa1a0c.png)

**Comment by subhampro** [comment]
![image](https://user-images.githubusercontent.com/33375250/184965996-743224a9-2cb1-4dd5-b403-5deb2520d7db.png)

**Comment by paulierco** [comment]
Had the same issue, not sure if i'm doing something wrong.

**Comment by wow0000** [comment]
Hi, the configuration on the screenshots looks invalid.
Here is an example of working configuration
<img width="497" alt="image" src="https://user-images.githubusercontent.com/11897160/207964351-1e17e101-b1b9-4d1c-ba04-71ddc9f51720.png">
54.xxx.xxx.xxx is the client public IP
141.xxx.xxx.xxx is the GRE server IP
