### ISSUE TITLE
netsh - The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by sbbbv** [wow0000/GRE_Tunnel#3]
Hello.

I think there's a little problem with custom naming of GRE interface.

"
Arguments: gre_tunnel.exe GRE_BIND_IP GRE_SERVER INTERFACE_IP GATEWAY_IP [CIDR (30)] [ADAPTER_NAME]

c:\Temp\Release>GRETunnel.exe 10.30.154.33 10.30.151.62 172.16.154.2 172.16.154.1 30 151
GRE Tunnel for Windows

18/02/2023 01:45:53 [DEBUG] Starting GRE Application
My IP on the GRE network: 172.16.154.2/30
GRE server IP           : 10.30.151.62
GRE server IP (Gateway) : 172.16.154.1
GRE binding IP          : 10.30.154.33
Adapter name            : 151

18/02/2023 01:45:53 [INFO] netsh interface ip set address name="151" static 172.16.154.2 255.255.255.252 172.16.154.1 300
The filename, directory name, or volume label syntax is incorrect.

18/02/2023 01:45:53 [INFO] netsh interface ip set subinterface "151" mtu=1476 store=persistent
The filename, directory name, or volume label syntax is incorrect.

"

**Comment by wow0000** [comment]
Hi, could you try with letters ? I'm not sure that "151" is a valid interface name

**Comment by sbbbv** [comment]
The same with any other name.
Windows 2019. Starting GRETunnel.exe with admin right.

"27/02/2023 02:06:03 [INFO] netsh interface ip set subinterface "interface" mtu=1476 store=persistent
The filename, directory name, or volume label syntax is incorrect."

"27/02/2023 02:07:07 [INFO] netsh interface ip set subinterface "Ethernet2" mtu=1476 store=persistent
The filename, directory name, or volume label syntax is incorrect."

"27/02/2023 02:10:32 [INFO] netsh interface ip set subinterface "blabla" mtu=1476 store=persistent
The filename, directory name, or volume label syntax is incorrect."

**Comment by wow0000** [comment]
On which version of windows are you ?

**Comment by sbbbv** [comment]
> On which version of windows are you ?

Windows Server 2019.
Microsoft Windows [Version 10.0.17763.4010]

**Comment by wow0000** [comment]
Should be fixed thanks to #5
